FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json vite.config.* ./
RUN npm ci --legacy-peer-deps
COPY public ./public
COPY src ./src  
COPY index.html ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
