name: Blogy-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend image to DockerHub
        run: |
          cd ./blogy-frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-frontend:latest
      
      - name: Build and push backend image to DockerHub
        run: |
          cd ./blogy-backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-frontend
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-backend
            sudo docker stop blogy-frontend
            sudo docker stop blogy-backend
            sudo docker rm -f blogy-frontend 
            sudo docker rm -f blogy-backend
            sudo docker run -d -p 80:80 --name blogy-frontend \
            -e VITE_API_URL=http://3.109.216.120:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-frontend
            sudo docker run -d -p 3000:3000 --name blogy-backend \
             -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
             -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
             -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
             -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
             -e PORT="3000" \
             ${{ secrets.DOCKERHUB_USERNAME }}/blogy-img-backend
               
