#BLOCK 1: WORKFLOW METADATA
name: Deploy-blog
# BLOCK 2: TRIGGERS (When to Run)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#BLOCK 3: JOBS (What Work to Do)
jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps: 
        - name: Checout Code
          uses: actions/checkout@v3
    # Backend Build + Docker Push
        - name: build backend
          run: |
            cd server
            npm ci
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bogy-backend:latest .
        - name: push backend to hub
          uses: appleboy/ssh-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Push backend image to docker hub
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bogy-backend:latest
    # Backend Frontend + Docker Push
        - name: build frontend
          run: |
            cd .
            npm ci
            npm build
            docker build -t ${{ secrets.DOCKER.USERNMAE }}/bogy-frontend:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/bogy-backend:latest

  #Deploy to EC2 K8S
        - name: Deploy to EC2 K8S
          uses: appleboy/ssh-action@v3
          with:
            host: ${{ secrets.EC2_PUBLIC_IP }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              kubectl set image deployment/frontend blogy-frontend=${{ secrets.DOCKERHUB_USERNAME }}/blogy-frontend:latest
              kubectl set image deployment/backend blogy-backend=${{ secrets.DOCKERHUB_USERNAME }}/blogy-backend:latest
              kubectl rollout status deployment/frontend
              kubectl rollout status deployment/backend














